[[redirects]]
  from = "https://whoownswhat.nyc/*"
  to = "https://whoownswhat.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "https://wow-django.netlify.app/*"
  to = "https://whoownswhat.justfix.org"
  status = 301
  force = true

[[redirects]]
  from = "https://demo-whoownswhat.justfix.nyc/en/wowza/*"
  to = "https://demo-whoownswhat.justfix.org/en/"
  status = 301
  force = true

[[redirects]]
  from = "https://demo-whoownswhat.justfix.nyc/*"
  to = "https://demo-whoownswhat.justfix.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://whoownswhat.justfix.nyc/*"
  to = "https://whoownswhat.justfix.org/:splat"
  status = 301
  force = true

# Make sure accessing static files returns a 404
[[redirects]]
  from = "/static/*"
  to = "/not-found.html"
  status = 404

# Prevent default Netlify 404 page from appearing on page refresh.
# Note: this redirect rule must come AFTER any other rule to prevent overriding 
# See https://stackoverflow.com/a/64842020 for more details
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "client/"

  # Directory that contains the deploy-ready HTML files and assets generated by
  # the build. This is relative to the base directory if one has been set, or the
  # root directory if a base has not been set.
  publish = "build/"

  # Default build command.
  #
  # Note that we are removing `node_modules/.cache` because Netlify caches
  # `node_modules` by default, and Create React App currently over-uses
  # this cache because, without clearing it, changes to `browserslist`
  # in our package.json won't propagate. For more details on this, see
  # https://github.com/JustFixNYC/who-owns-what/pull/335.
  command = "rm -rf node_modules/.cache && yarn build"
