import React from 'react';
import LegalFooter from 'components/LegalFooter';

const PrivacyPolicyPage = () => {
  return (
    <div className="PrivacyPolicy Page">
      <div className="Page__content">
      
        <h4 style={{fontSize: "3.2rem"}}>WhoOwnsWhat — Privacy Policy</h4>
        <p>Effective Date: October 18th, 2018 </p>
        <h4> Introduction </h4>
        <p>
          Welcome! You have arrived at <a href='https://whoownswhat.justfix.nyc' target='_blank'>https://whoownswhat.justfix.nyc</a> and/or are otherwise interacting with our Service (defined below), which is owned and operated by JustFix.nyc d/b/a WhoOwnsWhat (“WhoOwnsWhat” or “we,” “our” or “us”). This Privacy Policy governs your use of any online service location (e.g., web site) that posts a link to this Privacy Policy (each a “Site” (including, without limitation, both mobile and online versions), and also applies to your use of interactive features, widgets, plug-ins, applications, content, downloads and/or other services that we own and control and make available through a Site and/or that posts a link to this Privacy Policy (collectively, the “Service”), regardless of how you access or use them, whether via personal computers, mobile devices or otherwise, but does not apply to data we receive from third parties, even if they use our technology to collect it except to the extent we combine such data with Personal Information (defined below) that we have ourselves collected under this Privacy Policy. This Privacy Policy does not apply to our data collection activities offline or otherwise outside of our Service (unless otherwise stated below), and does not govern the data practices of third parties that may interact with our Service. Also, it is limited to our practices and our Service includes access to third party content and services we do not control. Consult their privacy policies regarding their practices.
        </p>
        <p>
          To the extent we provide you notice on our Service of different or additional privacy policies or practices (e.g., at the point of our collection), those additional terms shall govern such data collection and use. 
        </p>
        <p> In addition, please review the Service’s Terms of Use, which govern your use of the Service, and include, among other things, grants of rights from you, limits on our liability and your remedies, mandatory arbitration, and waiver of jury trial and class actions. 
          <em>
            By using our Service, you agree to our Terms of Use and consent to our collection, use and sharing of your information and data, and other activities, as described below.
          </em>
        </p>
        <h4> 1. Information We Collect </h4>
          <h6> (a) Information About You That You Provide </h6>
            <p> WhoOwnsWhat, and/or its service providers, may collect information you provide directly to WhoOwnsWhat, its affiliates or partners, and/or its service providers. In addition, when you interact with third-party services, you may be able to provide information to those third parties. For more information on service provider data collection and practices, see “Information Collected Automatically” at Section 1(b), below. </p>
            <p> Information WhoOwnsWhat, its service providers and/or associated third-party services (defined below) may collect may include: (1) personally identifiable information, which is information that identifies you personally, such as your e-mail address, and residential address (“Personal Information”); and (2) demographic information, such as your zip code (“Demographic Information”). Except to the extent required by applicable law, Demographic Information is “non-Personal Information” (i.e., data that is not treated as Personal Information under this Privacy Policy). As permitted by applicable law, Personal Information, including, without limitation, WhoOwnsWhat-Collected PI (defined below), once “de-identified” (i.e., the removal or modification of personally identifiable elements or the extraction of non-personally identifiable elements) is also non-Personal Information and may be used and shared without obligation to you, except as prohibited by applicable law. To the extent any non-Personal Information is combined by or on behalf of WhoOwnsWhat with Personal Information WhoOwnsWhat itself collects directly from you on the Service (“WhoOwnsWhat-Collected PI”), WhoOwnsWhat will treat the combined data as WhoOwnsWhat-Collected PI under this Privacy Policy. </p>
            <p> If you submit your residential address to us, you represent that you are a New York state resident. </p>
          <h6> (b) Information Collected Automatically </h6> 
            <p> WhoOwnsWhat, its service providers, and/or associated third-party services may also automatically collect certain information about you when you access or use the Service (“Usage Information”). Usage Information may include IP address, device identifier, browser type, operating system, information about your use of the Service, and data regarding network connected hardware (e.g., computer or mobile device). Except to the extent required by applicable law, or to the extent Usage Information is combined by or on behalf of WhoOwnsWhat with WhoOwnsWhat-Collected PI, WhoOwnsWhat does not consider Usage Information (including, without limitation, unique identifiers) to be Personal Information or WhoOwnsWhat-Collected PI. For more information on service provider data collection and practices, see “Information We Share With Third Parties” at Section 3. For information on choices some third parties may offer you regarding automated data collection, see “Choices: Tracking and Communications Options” at Section 6. </p>
            <p> The methods that may be used on the Service to collect Usage Information include: </p>
            <ul>
              <li> Log Information: Log information is data about your use of the Service, such as IP address, browser type, Internet service provider, referring/exit pages, operating system, date/time stamps, and related data, and may be stored in log files. </li>
              <li> Information Collected by Cookies and Other Tracking Technologies: cookies and web beacons (also known as “tracking pixels”), and other tracking technologies now and hereafter developed (“Tracking Technologies”) may be used to collect information about interactions with the Service or e-mails, including information about your browsing and purchasing behavior.</li>
              <li> Cookies. A cookie is a small text file that is stored on a user’s device, which may be session ID cookies or tracking cookies. Session cookies make it easier for you to navigate the Service and expire when you close your browser. Tracking cookies remain longer and help in understanding how you use the Service, and enhance your user experience. Cookies may remain on your hard drive for an extended period of time. If you use your browser’s method of blocking or removing cookies, some but not all types of cookies may be deleted and/or blocked and as a result some features and functionalities of the Service may not work. A Flash cookie (or locally shared object) is a data file which may be placed on a device via the Adobe Flash plug-in that may be built-in to or downloaded by you to your device. HTML5 cookies can be programmed through HTML5 local storage. Flash cookies and HTML 5 cookies are locally stored on your device other than in the browser and browser settings won’t control them. To identify certain types of local shared objects on your computer and adjust your settings, please visit: www.macromedia.com/support. The Service may associate some or all of these types of cookies with your devices. </li>
              <li> Web Beacons (“Tracking Pixels”). Web beacons are small graphic images, also known as “Internet tags” or “clear gifs,” embedded in web pages and e-mail messages. Web beacons may be used, without limitation, to count the number of visitors to the Service, to monitor how users navigate the Service, and to count content views. Some information about your use of the Service and certain third-party services may be collected using Tracking Technologies across time and services, and used by WhoOwnsWhat and third parties for purposes such as to associate different devices you use, and deliver relevant ads and/or other content to you on the Service and certain third-party services. See “Choices: Tracking and Communications Options” at Section 6 regarding certain choices regarding these activities. </li>
            </ul>
          <h6>(c) Information WhoOwnsWhat Collects From Partners and Other Sources</h6>
            <p> WhoOwnsWhat may also obtain information about you from other sources, including service providers, third-party services, and partners or affiliates and combine that with WhoOwnsWhat-Collected PI. For example, you may provide Personal Information to JustFix, a sister website of WhoOwnsWhat, in order to link your WhoOwnsWhat information to your JustFix account. </p>
            <p> Notwithstanding anything to the contrary, except to the extent such data combined by or on behalf of WhoOwnsWhat with WhoOwnsWhat-Collected PI, this Privacy Policy is not intended to limit WhoOwnsWhat’s activities regarding such third-party-sourced, or non-Service-sourced, information (including Personal Information) and limitations on WhoOwnsWhat’s activities regarding WhoOwnsWhat-Collected PI (e.g., on sharing) described in this Privacy Policy do not apply. WhoOwnsWhat is not responsible or liable for the accuracy of the information provided by third parties or for third party policies or practices.</p>
        <h4> 2. How We Use The Information We Obtain </h4>
          <p> Generally. WhoOwnsWhat may use information about you, including WhoOwnsWhat-Collected PI and other Personal Information, for any purposes not inconsistent with this Privacy Policy, or our statements at the point of collection, and not prohibited by applicable law, including, without limitation, the following: (1) to provide you with information or services ; (2) to enable you to participate in a variety of the Service’s features; (3) to verify your information; (4) to manage and administer the Service; (5) to improve the Service or create new service offerings, to customize your experience on any of the Service, or to serve you, or suggest to you, specific content that may be most relevant to you; (6) to contact you with regard to your use of any of the Service and, in our discretion, changes to the any of the Service and/or any of the Service’s’ policies; (7) to prevent unauthorized, improper or illegal activities on the Service; (8) for internal business purposes; and (9) for purposes disclosed at the time you provide your information or as otherwise set forth in this Privacy Policy or for any other legal purpose not inconsistent with this Privacy Policy or our Terms of Use. We will not use Personal Information provided by you in a customer inquiry communication to contact you for marketing purposes unrelated to your request unless you agree otherwise. </p>
          <p> Advertising, Content Management and Location-Based Services. We may also use your Personal Information, Demographic Information or Usage Information that we collect about you to provide advertisements or content to you; and to understand the usefulness and effectiveness of the advertisements or content that have been delivered to you. For more on advertising, see “Third-Party Content, Third-Party Services, Advertising and Analytics” at Section 4. </p>
        <h4> 3. Information We Share With Third Parties </h4>
          <p> WhoOwnsWhat may share non-Personal Information, anonymized Personal Information, and Personal Information that is not deemed WhoOwnsWhat-Collected PI hereunder, with third parties and their affiliates for any purpose. WhoOwnsWhat’s sharing of WhoOwnsWhat-Collected PI is, however, subject to the following: </p>
          <ul>
            <li> Marketing. Subject to your communications choices explained in Section 6, we may use your Personal Information to send you marketing communications. WhoOwnsWhat may share your WhoOwnsWhat–Collected PI with its affiliates, and with those partners we think you might be interested in, for their own marketing purposes. </li>
            <li> Your Disclosure or Consent: As more fully described in Section 5 (“Information You Disclose Publicly or to Others”) and Section 3 (“Information We Share With Third Parties”), your activities on the Service may, by their nature, result in the sharing of your Personal Information with third parties, and by engaging in these activities you consent to that and further sharing, and your Personal Information may be disclosed to third parties. Such third party data receipt and collection is subject to the privacy and business practices of that third party, not WhoOwnsWhat. WhoOwnsWhat may also share any information about you (including, without limitation, WhoOwnsWhat-Collected PI) for any purposes not inconsistent with this Privacy Policy, or our statements as the point of collection, and not prohibited by applicable law, including but not limited to:</li>
            <li> Partners and Affiliates. WhoOwnsWhat’s affiliates and partners may receive, or be given access to your information, including Personal Information. For example, WhoOwnsWhat allows individuals to connect with JustFix account users, a sister website of WhoOwnsWhat. We may share your Personal Information to JustFix in order to facilitate potential communications and connections (e.g., e-mail) between WhoOwnsWhat and JustFix users to build a more robust community. We are not responsible for partner or affiliate technologies or activities or any information they collect directly from you. </li>
            <li> Service Providers. WhoOwnsWhat’s agents, vendors, consultants, and other service providers  may receive, or be given access to your information, including, without limitation, Personal Information, Demographic Information, and Usage Information, in connection with their work on WhoOwnsWhat’s behalf, provided however, WhoOwnsWhat does not authorize its service providers to use WhoOwnsWhat-Collected PI provided by WhoOwnsWhat to the service providers to send you direct marketing messages other than related to the WhoOwnsWhat absent your consent. However, third-party analytics and other service providers, and Third-Party Operators of associated third-party services, may set and access their own Tracking Technologies on your device, and they may otherwise collect or have access to information about you, potentially including Personal Information, about you. We are not responsible for those third party technologies or activities arising out of them or any information they collect directly from you. Some may offer you certain choices regarding their practices. For more information, see “Choices: Tracking and Communications Options” at Section 6.</li>
            <li> Corporate Transactions. WhoOwnsWhat may share your Personal Information, including, without limitation, WhoOwnsWhat-Collected PI, as well as your non-Personal Information, in connection with or during negotiations of any proposed or actual merger, purchase, sale, joint venture, or any other type of acquisition or business combination of all or any portion of WhoOwnsWhat assets, or transfer of all or a portion of WhoOwnsWhat’s business to another company (“Corporate Transactions”).</li>
            <li> Government Agencies and Civic Organizations. WhoOwnsWhat may give or provide access to anonymized Personal Information about you to government agencies and civic organizations to understand ongoing civic issues and ultimately provide improved services and education to consumers such as yourself.</li>
            <li> When You Request Information From or Provide Information to Third Parties. You may be presented with an option on our Service to have us send certain information to third parties or give them access to it. If you choose to do so, your Personal Information, including WhoOwnsWhat-Collected PI, and other information may be disclosed to such third parties and all information disclosed will be subject to the third-party privacy policies and practices of such third parties. In addition, third parties may store, collect or otherwise have access to your information when you interact with their Tracking Technologies, associated third-party services (e.g., third party operator’s content, tools, plug-ins, apps or ads on our Service) or link to them from our Service. We are not responsible for the privacy policies and practices of such third parties and, therefore, you should review such third-party privacy policies and practices of such third parties prior to requesting information from or otherwise interacting with them.</li>
            <li> To Deliver Advertising. We, and others we work with (e.g., third party publishers, advertisers and advertising services providers) may use your Personal Information, Demographic Information and/or Usage Information we have collected in connection with the Service to target and deliver content and advertisements to you and other users, both on and off of our Service. Further, by using the Service, you consent to the use of your Personal Information and your Service activity information (including regarding your content consumption) in, or in connection with, sponsored content and advertisements shown to your connections or other users.</li>
            <li> To Protect WhoOwnsWhat and Others. To the fullest extent not prohibited by applicable law, we may also disclose your information if we believe in good faith that doing so is necessary or appropriate to: (i) protect or defend the rights, safety or property of WhoOwnsWhat or third parties (including through the enforcement of this Policy, our Terms of Use, and other applicable agreements and policies); (ii) comply with legal and regulatory obligations and government requests (e.g., pursuant to law enforcement inquiries, subpoenas or court orders); (iii) comply with our obligations and commitments to safeguard the privacy and security of your information; or (iv) prevent unauthorized, improper or illegal activities on the Service. Further, we may disclose information about you as otherwise permitted under our Terms of Use or as specifically disclosed when we collect information from you. Additionally, if you notify us that you believe your rights have been violated in connection with the Service or another user of the Service, we may disclose information about you to the extent necessary to evaluate and respond to your concern. To the fullest extent not prohibited by applicable law, we have complete discretion in electing to make or not make such disclosures, and to contest or not contest requests for such disclosures, all without notice to you.</li>
          </ul>
        <h4> 4. Third-Party Content, Third-Party Services, Advertising And Analytics </h4>
          <p> The Service may contain content that is supplied by a Third-Party Operator, and those third parties may collect Usage Data and your device identifier when such content is served to you. Associated third-party services may also be available via the Service. We are not responsible for the data collection and privacy practices employed by such third parties or their services and they may themselves be collecting data from you and may be sharing it with us and/or others. These third parties and their services may also associate their Tracking Technologies with you, track you across sites and time, and may or may not have their own published privacy policies. </p>
          <p> In addition, when you are on the Service you may be directed to other services that are operated and controlled by third parties that we do not control. For example, if you “click” on a link, the “click” may take you off the Service onto a different site. We encourage you to note when you leave our Service and to review the third-party privacy policies of all third-party locations and exercise caution in connection with them. </p>
          <p> Be sure to review any available privacy policies and notices before submitting any Personal Information to a third party or its services, or otherwise interacting with third-party services or other locations you link to from our Service, and exercise caution in connection with them. We are not responsible for the availability, completeness or accuracy of such third parties’ policies or notices.</p>
          <p> WhoOwnsWhat may engage and work with third parties to serve advertisements on WhoOwnsWhat’s behalf on the Service, and/or on other websites, mobile apps and online services, and/or to provide analytics about the use of the Service and the performance of WhoOwnsWhat’s ads and content on the Service and on third-party services. In addition, WhoOwnsWhat may participate in online advertising networks and exchanges that display relevant advertisements to the WhoOwnsWhat visitors, on third-party services, based on user interests as reflected in their browsing of the Service and certain third-party services. These entities may use cookies and other Tracking Technologies to automatically collect information about you and your activities, such as registering a unique identifier for your device and tying that to your online activities on and off of the Service. WhoOwnsWhat may use this information to, among other things, analyze and track data, determine the popularity of certain content, deliver advertising and content targeted to your interests on the Service and third-party services and better understand your online activity.</p>
          <p> Some information about your use of the Service and certain third-party services may be collected using Tracking Technologies across time and services and used by WhoOwnsWhat and third parties for purposes such as to associate different devices you use, and deliver relevant and retargeted ads (“Interest-based Ads”) and/or other content to you or others on the Service and certain third-party services. </p>
          <p> As permitted by applicable law, WhoOwnsWhat is not responsible for third parties or third-party services associated with advertising and analytics services, and related tracking activities. Consult their privacy policies and notices for information on their practices and see “Choices: Tracking and Communications Options” at Section 6 regarding certain choices some of them may offer you.</p>
        <h4> 5. Information You Disclose Publicly Or To Others </h4> 
          <p> The Service may permit you to submit messages, text, illustrations, files, images, graphics, photos, comments, responses, sounds, music, videos, information, content, ratings, reviews, data, questions, suggestions, personally identifiable information, or other information or materials and the ideas contained therein (collectively, “User-Generated Content” or “UGC”), such as on a public profile or public message board.  We or others may store, display, reproduce, publish, distribute or otherwise use User-Generated Content online or offline in any media or format (currently existing or hereafter developed) and may or may not attribute it to you.  Others may have access to this User-Generated Content and may have the ability to share it with third parties.  If you choose to submit UGC to any public area of the Service, your UGC will be considered “public” and will be accessible by anyone, including WhoOwnsWhat. Notwithstanding anything to the contrary, Personal Information included in UGC that is public or semi-public is not subject to WhoOwnsWhat’s usage or sharing limitations, or other obligations, regarding WhoOwnsWhat-Collected PI or other Personal Information under this Privacy Policy or otherwise, and may be used and shared by WhoOwnsWhat and third parties to the fullest extent not prohibited by applicable law. Please think carefully before deciding what information you share, including Personal Information, in connection with your User-Generated Content.  Please note that WhoOwnsWhat does not control who will have access to the information that you choose to make available to others, and cannot ensure that parties who have access to such information will respect your privacy or keep it secure.  We are not responsible for the privacy or security of any information that you make publicly available on the Service or what others do with information you share with them on the Service.  We are not responsible for the accuracy, use or misuse of any User-Generated Content that you disclose or receive from third parties through the Service.  As permitted by applicable law, except where we have otherwise explicitly agreed, we may also publish your name, voice, likeness and other Personal Information that is part of your User-Generated Content, and we may use the content, or any portion of the content, for advertising, marketing, publicity and promotional activities without renumeration, or other obligation to you. For full terms and conditions regarding User-Generated Content you submit to the Service, please review our Terms of Use. </p>
        <h4> 6. Choices: Tracking And Communications Options </h4> 
          <h6> (a) Accessing And Changing Information. </h6>
            <p> If you submitted personal information to WhoOwnsWhat, such as an e-mail or physical address, you may revise such personal information we have retained by emailing us at <a href='mailto:hello@justfix.nyc' target='_blank'>hello@justfix.nyc</a>. </p>
          <h6> (b) Tracking Technologies Generally. </h6>
            <p> Regular cookies may generally be disabled or removed by tools available as part of most commercial browsers, and in some instances blocked in the future by selecting certain settings. Browsers offer different functionalities and options so you may need to set them separately. Also, tools from commercial browsers may not be effective with regard to Flash cookies (also known as locally shared objects), HTML5 cookies or other Tracking Technologies. For information on disabling Flash cookies, go to Adobe’s website <a href='http://helpx.adobe.com/flash-player/kb/disable-third-party-local-shared.html' target='_blank'>http://helpx.adobe.com/flash-player/kb/disable-third-party-local-shared.html</a>. Please be aware that if you disable or remove these technologies some parts of the Service may not work and that when you revisit the Service your ability to limit browser-based Tracking Technologies is subject to your browser settings and limitations. </p>
            <p> Your browser settings may allow you to automatically transmit a “Do Not Track” signal to online services you visit. Note, however, WhoOwnsWhat currently does not alter WhoOwnsWhat’s practices when WhoOwnsWhat receives a “Do Not Track” signal from a visitor’s browser. Some third parties, however, may also offer you choices regarding their Tracking Technologies. One way to potentially identify cookies on our Site is to add the free Ghostery plug-in to your browser (www.ghostery.com), which according to Ghostery will display for you traditional, browser-based cookies associated with the web sites (but not mobile apps) you visit and privacy and opt-out policies and options of the parties operating those cookies. WhoOwnsWhat is not responsible for the completeness or accuracy of this tool or third party choice notices or mechanisms. For specific information on some of the choice options offered by third party analytics and advertising providers, see the next subsection. </p>
          <h6> (c) Analytics and Interest-Based Advertising.</h6>
            <p> WhoOwnsWhat may use Google Analytics, Adobe Analytics or other service providers for analytics services. These analytics services may use cookies and other Tracking Technologies to help WhoOwnsWhat analyze how users use the Service. Information generated by these services (e.g., your IP address and other Usage Information) may be transmitted to and stored by Google Analytics, Adobe Analytics and other service providers on servers in the U.S. (or elsewhere) and these service providers may use this information for purposes such as evaluating your use of the Service, compiling statistic reports on the Service’s activity, and providing other services relating to Service activity and other Internet usage. You may exercise choices regarding the use of cookies from Google Analytics by going to <a href='https://tools.google.com/dlpage/gaoptout' target='_blank'>https://tools.google.com/dlpage/gaoptout</a> or downloading the Google Analytics Opt-out Browser Add-on. You may exercise choices regarding the use of cookies from Adobe Analytics by going to http://www.adobe.com/privacy/opt-out.html. </p>
          <h6> (d) Communications and Marketing.</h6>
            <p> You can opt out of receiving certain promotional communications (emails or text messaging) from WhoOwnsWhat at any time by (i) for promotional e-mails, by following the instructions as provided in emails to click on the unsubscribe link, or if available by changing your communication preferences by logging onto your account; and (ii) for text messages by following the instructions as provided in text messages from WhoOwnsWhat to text the word, “STOP”. Please note that your opt-out is limited to the e-mail address or phone number used and will not affect subsequent subscriptions. If you opt-out of only certain communications, other subscriptions may continue. Even if you opt out of receiving promotional communications WhoOwnsWhat may, subject to applicable law, continue to send you non-promotional communications, such as those about your account, transactions, servicing, or WhoOwnsWhat’s ongoing business relations. </p>
        <h4> 7. International Data Transfers </h4>
          <p> Our Service is operated in the United States and intended for users located in the United States. If you are located outside of the United States, please be aware that information we may collect, including Personal Information, will be transferred to, and processed, stored and used in the United States. The data protection laws in the United States may differ from those of the country in which you are located, and your Personal Information may be subject to access requests from governments, courts, or law enforcement in the United States according to laws of the United States. By using the Service or providing us with any information, you consent to the transfer to, and processing, usage, sharing and storage of your information, including Personal Information, in the United States as set forth in this Privacy Policy. </p>
        <h4> 8. Data Security And Monitoring </h4>
          <p> We endeavor to incorporate commercially reasonable safeguards to help protect and secure your Personal Information. However, no data transmission over the Internet, mobile networks, wireless transmission or electronic storage of information can be guaranteed to be 100% secure. Please note that we cannot ensure the security of any information you transmit to us, and you use our Service, and provide us with your information, at your own risk. </p>
        <h4> 9. Updates To Our Privacy Policy </h4>
           <p> We reserve the right to modify this privacy policy at any time, so please review it frequently and at least each time you submit personal information to the Service. If we make material changes to this policy, we will notify you here on this page or by means of a notice on our homepage. The date of the most recent revisions will also appear on this page. Unless stated otherwise, our current privacy policy applies to all information that we have about you. </p>
        <h4> 10. Contact Us </h4>
           <p> If you have any questions regarding this Privacy Policy or our privacy and data security practices, please contact us at <a href='mailto:hello@justfix.nyc' target='_blank'>hello@justfix.nyc</a>. </p>
      </div>
      <LegalFooter />
    </div>  
  );
}

export default PrivacyPolicyPage;