import React from 'react';
import LegalFooter from 'components/LegalFooter';

const TermsOfUsePage = () => {
  return (
    <div className="TermsOfUse Page">
      <div className="Page__content">
        <h4 style={{fontSize: "3.2rem"}}>WhoOwnsWhat — Terms of Use</h4>
          <p> Effective Date: October 18th, 2018 </p>
          <p><b><em>Please read this agreement carefully. It sets forth the legally binding terms and conditions for your use of the service, such as your grants and waivers of rights, the limitations of our liability, your indemnity of us, and arbitration of certain disputes.</em></b></p>
        <h4> Introduction And Overview </h4>
          <p> Welcome! You have arrived at <a href='https://.whoownswhat.justfix.nyc' target='_blank'>https://.whoownswhat.justfix.nyc</a> and/or are otherwise interacting with our Service (defined below), which is owned and operated by JustFix.nyc d/b/a WhoOwnsWhat (collectively, “WhoOwnsWhat,” “we,” “our,” or “us”). These Terms govern your use of any online service location (e.g., website) that posts a link to these Terms (“Site”) (including both mobile and online versions). It also applies to your use of all features, widgets, plug-ins, applications, content, downloads and/or other services that we own and control and make available through the Site (collectively, with the Site, the “Service”), regardless of how you access or use it, whether via computer, mobile device or otherwise. By using the Service, you acknowledge and accept the Service’s Privacy Policy and consent to the collection and use of your data in accordance therewith. By interacting with and/or using the Service, you signify your assent and agreement to these Terms. If you do not agree to these Terms, you must not use the Service. </p>
          <p> In some instances, both these Terms and separate guidelines, rules, or terms of use setting forth additional or different terms and/or conditions will apply to your use of the Service or to a service or product offered via the Service (in each such instance, and collectively “Additional Terms”). To the extent there is a conflict between these Terms and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly state otherwise. Please also review the Service’s <a href='https://whoownswhat.justfix.nyc/privacy-policy' target='_blank'>Privacy Policy</a> which you accept by using the Service. </p>
        <h4> 1. Rights And Responsibilities Terms </h4>
         <h6> (a) Service Content, Ownership, Limited License, And Rights Of Others </h6>
          <p> Content. The Service contains a variety of: (i) materials and other items relating to WhoOwnsWhat and its products and services, and similar items from our licensors and other third parties, including all layout, information, articles, posts, text, data, files, images, scripts, designs, graphics, button icons, instructions, illustrations, photographs, pictures, advertising copy, URLs, technology, software, interactive features, the “look and feel” of the Service, and the compilation, assembly, and arrangement of the materials of the Service and any and all copyrightable material (including source and object code); (ii) trademarks, logos, trade names, trade dress, service marks, and trade identities of various parties, including those of WhoOwnsWhat (collectively, “Trademarks”); and (iii) other forms of intellectual property (all of the foregoing, collectively “Content”).</p> 
          <p> Ownership. The Service and the Content are owned or controlled by WhoOwnsWhat and our licensors and certain other third parties. All rights, titles, and interest in and to the Content available via the Service is the property of WhoOwnsWhat or our licensors or certain other third parties, and is protected by U.S. and international copyright, trademark, trade dress, patent and/or other intellectual property and other rights and laws to the fullest extent possible. WhoOwnsWhat owns the copyright in the selection, compilation, assembly, arrangement, and enhancement of the Content on the Service.</p> 
          <p> Limited License. Subject to your strict compliance with these Terms and the Additional Terms, WhoOwnsWhat grants you a limited, non-exclusive, revocable, non-assignable, personal, and non-transferable license to download and copy (temporary storage only of web site content), display, view, use, play the Content on a personal computer, browser, laptop, tablet, mobile phone or other wireless device, or other Internet-enabled device (each, a “Device”), and/or print one copy of the Content (excluding source and object code in raw form or otherwise) as it is displayed to you, in each case for your personal, non-commercial use only. The foregoing limited license (i) does not give you any ownership of, or any other intellectual property interest in, any Content, and (ii) may be immediately suspended or terminated for any reason, in WhoOwnsWhat’s sole discretion, and without advance notice or liability. In some instances, we may permit you to have greater access to and use of Content subject to certain Additional Terms. Your breach of any of these Terms or Additional Terms automatically terminates this license.</p> 
          <p> Reservation of All Rights Not Granted As To Content and Service. These Terms and any applicable Additional Terms include only narrow, limited grants of rights to Content and to use and access the Service. No right or license may be construed, under any legal theory, by implication, estoppel, industry custom, or otherwise. All rights not expressly granted to you are reserved by WhoOwnsWhat and its licensors and other third parties. Any unauthorized use of any Content or the Service for any purpose is prohibited.</p> 
         <h6> (b) Content You Submit And Community Usage Rules </h6>
          <p> User–Generated Content. From time to time, WhoOwnsWhat may want to use your Submissions (defined below) for the purposes of marketing and advertising the Services. In such instances, WhoOwnsWhat will ask your permission to use your Submissions and will contact you by way of any contact information you may provide to WhoOwnsWhat. You agree to permit WhoOwnsWhat to contact you for such permission. Should you give WhoOwnsWhat permission to use your Submissions, that permission grants WhoOwnsWhat a non-exclusive, unrestricted, unconditional, unlimited, worldwide, revocable, and cost-free right and license to use, copy, record, distribute, reproduce, disclose, sublicense (through multiple levels), display, publicly perform, transmit, publish, broadcast, translate, make derivative works of, and otherwise use in any manner whatsoever, all or any portion of any material or information you post or submit to us (on or via the Service, or by means other than the Service) (“Submissions” or “UGC”), and derivative works thereof, for any purpose whatsoever in all formats, on or through any means or medium now known or hereafter developed, and with any technology or devices now known or hereafter developed, and to advertise, market, and promote the same, all without any obligation to you not required by applicable law, or explicit terms of our Privacy Policy or applicable Additional Terms. As permitted by applicable law, and subject to your permission as explained above and any explicit terms of our Privacy Policy and applicable Additional Terms, you also consent to our use and association of your name (and, if part of a Submission, your likeness) in connection with your Submissions and derivatives thereof. As permitted by applicable law, you hereby waive, and you agree to waive, any moral rights (including attribution and integrity) that you may have in any Submissions, even if it is altered or changed in a manner not agreeable to you. To the extent not waivable, you irrevocably agree not to exercise such rights (if any) in a manner that interferes with any exercise of the granted rights. You understand that you will not receive any fees, sums, consideration, or remuneration for any of the rights granted in this Section. In addition, we and our successors, assigns and licensees retain all of the rights held by members of the general public with regard to your Submissions. Our receipt of your Submissions is not an admission of their novelty, priority, or originality, and it does not impair our right to contest existing or future intellectual property rights relating to your Submissions. If you decide to revoke such permission for WhoOwnsWhat’s use of your Submissions, such revocation must be in writing to WhoOwnsWhat and comply with the notice provisions set forth below.</p> 
         <h6> (c) Service And Content Use Restrictions </h6>
          <p> Service Use Restrictions. You agree that you will not: (i) use the Service for any political or commercial purpose (including, without limitation, for purposes of advertising, soliciting funds, collecting product prices, and selling products); (ii) use any meta tags or any other “hidden text” utilizing any Trademarks; (iii) engage in any activities through or in connection with the Service that seek to attempt to or do harm any individuals or entities or are unlawful, offensive, obscene, lewd, lascivious, filthy, violent, threatening, harassing, or abusive, or that violate any right of any third party, or are otherwise objectionable to WhoOwnsWhat; (iv) reverse engineer, decompile, disassemble, reverse assemble, or modify any Service source or object code or any software or other products, services, or processes accessible through any portion of the Service; (v) engage in any activity that interferes with a user’s access to the Service or the proper operation of the Service, or otherwise causes harm to the Service, WhoOwnsWhat, or other users of the Service; (vi) interfere with or circumvent any security feature of the Service or any feature that restricts or enforces limitations on use of or access to the Service or the Content; (vii) harvest or otherwise collect or store any information (including personally identifiable information about other users of the Service, including email addresses, without the express consent of such users); (viii) attempt to gain unauthorized access to the Service, other computer systems or networks connected to the Service; or (ix) otherwise violate these Terms or any applicable Additional Terms.</p>
          <p> Content Use Restrictions. Without limiting the restrictions in Section 1(b) above or in any applicable Additional Terms, you also agree that, in using the Service, you: (i) will not monitor, gather, copy, or distribute the Content (except as may be a result of standard search engine activity or use of a standard browser) on the Service by using any robot, rover, “bot”, spider, scraper, crawler, spyware, engine, device, software, extraction tool, or any other automatic device, utility, or manual process of any kind; (ii) will not frame or utilize framing techniques to enclose any such Content (including any images, text, or page layout); (iii) will keep intact all Trademark, copyright, and other intellectual property notices contained in such Content; (iv) will not use such Content in a manner that suggests an unauthorized association with any of our or our licensors’ products, services, or brands; (v) will not make any modifications to such Content (other than to the extent of your permitted use of the WhoOwnsWhat Licensed Elements, if applicable); (vi) will not copy, modify, reproduce, archive, sell, lease, rent, exchange, create derivative works from, publish by hard copy or electronic means, publicly perform, display, disseminate, distribute, broadcast, retransmit, circulate or transfer to any third party or on any third-party application or website, or otherwise use or exploit such Content in any way for any purpose except as specifically permitted by these Terms or any applicable Additional Terms or with the prior written consent of an officer of WhoOwnsWhat or, in the case of Content from a licensor, the owner of the Content or UGC; and (vii) will not insert any code or product to manipulate such Content in any way that adversely affects any user experience of the Service.</p> 
          <p> Availability of Service and Content. WhoOwnsWhat may immediately suspend or terminate the availability of the Service and Content (and any elements and features of them), in whole or in part, for any reason, in WhoOwnsWhat’s sole discretion, and without advance notice or liability. </p>
         <h6> (d) Links By You To The Service </h6>
          <p> We grant you a limited, non-exclusive, revocable, non-assignable, personal, and non-transferable license to create hyperlinks to the Service, so long as: (a) the links only incorporate text, and do not use any Trademarks, (b) the links and the content on your website do not suggest any affiliation with WhoOwnsWhat or cause any other confusion, and (c) the links and the content on your website do not portray WhoOwnsWhat or its products or services in a false, misleading, derogatory, or otherwise offensive matter, and do not contain content that is unlawful, offensive, obscene, lewd, lascivious, filthy, violent, threatening, harassing, or abusive, or that violate any right of any third party or are otherwise objectionable to WhoOwnsWhat. WhoOwnsWhat reserves the right to suspend or prohibit linking to the Service for any reason, in its sole discretion, without advance notice or any liability of any kind to you or any third party.</p>
        <h4> 2. Features Terms </h4>
         <h6> (a) Third-Party Services; Advertisements; Dealings With Third Parties </h6> 
          <p> Third-Party Content and Sites; Advertisements. The Service may contain or may interact with or otherwise be associated with third party platforms, services, plug-ins, applications, ads, tools and/or other content, and/or links to third-party websites or other services that are not owned, controlled or operated by WhoOwnsWhat (collectively, “Third-Party Services”), including services operated by advertisers, licensors, licensees, e-commerce partners and certain other third parties who may have business relationships with WhoOwnsWhat. We may also host our content, apps and tools on Third-Party Services. WhoOwnsWhat may have no control over the content, operations, policies, terms, or other elements of Third-Party Services, and WhoOwnsWhat does not assume any obligation to review any Third-Party Services. WhoOwnsWhat does not necessarily endorse, approve, or sponsor any Third-Party Services, or any third-party content, advertising, information, materials, products, services, or other items. Furthermore, WhoOwnsWhat is not responsible for the quality or delivery of the products or services offered, accessed, obtained by or advertised at such Third-Party Services. Some Third-Party Services may impose fees for access to their resources through our Service and you are responsible for all such fees. Finally, as permitted by applicable law, we will under no circumstances be liable for any direct, indirect, incidental or special loss or other damage, whether arising from negligence, breach of contract, defamation, infringement of copyright or other intellectual property rights, caused by the exhibition, distribution or exploitation of any information or content contained within these Third-Party Services. Any activities you engage in connection with any of the same are subject to the privacy and other policies, terms and conditions of use and/or sale, and rules issued by the operator of the Third-Party Services. WhoOwnsWhat disclaims all liability in connection therewith, as permitted by applicable law. </p>
          <p> Dealings with Third Parties. Any interactions, correspondence, transactions, and other dealings that you have with any third parties found on or through the Service (including on or via Third Party-Services or advertisements) are solely between you and the third party (including issues related to the content of third-party advertisements, payments, delivery of goods, warranties (including product warranties), privacy and data security, and the like). For more information about the implications of activating these Third Party-Services and our use, storage and disclosure of information related to you and your use of such services within our Service, please see our Privacy Policy. As permitted by applicable law, you hereby agree to indemnify WhoOwnsWhat against all claims, injury and/or damages including, without limitation, attorneys’ fees, that arise out of your use of any Third Party-Service, including without limitation from any material that you post on any forum or social networking site in connection with us and/or any other claim related to your use of social media.</p>
          <p> As permitted by applicable law, you hereby grant WhoOwnsWhat an irrevocable perpetual license to use, reproduce, edit, create derivative works from, distribute, display, copy, transmit or otherwise use in any way, commercially or otherwise, any material that you may post to any social networking site or other Third-Party Service in connection with us or our Service. </p>
         <h6> (b) Wireless And Messaging Features </h6>
          <p> Wireless Features. The Service may offer certain features and services via your wireless Device. Features and services may include the ability to access the Service’s features, upload content to the Service, receive messages from the Service, and download applications to your wireless Device (collectively, “Wireless Features”). You agree to receive communications we may send through Wireless Features for which you are registered. Further, we may collect information related to your use of the Wireless Features. If you have registered via the Service for Wireless Features, then you agree to notify WhoOwnsWhat of any changes to your wireless contact information (including phone number). Standard message, data and other fees may be charged by your carrier, and carriers may deduct charges from pre-paid amounts or data allowances, for which you are responsible. Your carrier may prohibit or restrict certain Wireless Features and certain Wireless Features may be incompatible with your carrier or wireless Device. Contact your carrier with questions regarding these issues.</p>
         <h6> (c) Messages </h6>
          <p> Text Messages: You may be given opportunities to subscribe to various text marketing or other text messaging programs and by doing so, you consent to receive ongoing text alerts (including by auto-dialers) from us related to our various businesses and affiliates, which may include co-promotions with or about other parties, except that if the scope of your consent for a particular subscription is limited that subscription will be so limited. Such consent is not required to for any service aside from the text subscription itself. For each subscription, you will have the option to opt-out. Subsequent or different subscriptions will be unaffected by an opt-out. You consent to receive a text confirming any opt-out as well as non-marketing administrative or transactional messages. For subscriptions to recurring text messages, you may receive up to the number of text messages per month specified in your consent, or to which you later consent. Alerts auto-renew unless otherwise specified when you consented. You understand that we will send mobile text messages using automated technology. If you subscribe to text messages you represent that you are 18 years of age or older, or have obtained parental consent. Standard message, data and other fees may be charged by your carrier, and carriers may deduct charges from pre-paid amounts or data allowances, for which you are responsible. Contact your carrier for details. If we are charging a premium rate for text messages, that will be explained in the applicable subscription consent. Not all phones and/or carriers are supported. We are the sponsor of our text messages and may be contacted regarding them at: <a href='mailto:hello@justfix.nyc' target='_blank'>hello@justfix.nyc</a>.</p>
          <p> Email Messages: You may cancel or modify our email marketing communications you may receive from us by following the instructions contained within our promotional emails. This will not affect subsequent subscriptions and if your opt-out is limited to certain types of emails the opt-out will be so limited. Please note that we reserve the right to send you certain communications relating to your use of our Service, such as administrative and service announcements and these transactional messages may be unaffected if you choose to opt-out from receiving our marketing communications.</p>
         <h6> (d) Notices, Questions And Customer Service </h6>
          <p> You agree that: (1) we may give you notices of new, revised or changed terms and other important matters by prominently posting notice on the home page of the Service, or in another reasonable manner; and (2) we may contact you by mail or email sent to the address provided by you. All legal notices to us must be sent to 150 Court St, 2nd Floor, Brooklyn, NY 11201.</p>
          <p> If you have a question regarding using the Service, you may contact WhoOwnsWhat Customer Support by sending an email to <a href='mailto:hello@justfix.nyc' target='_blank'>hello@justfix.nyc</a>. You acknowledge that the provision of customer support is at WhoOwnsWhat’s sole discretion and that we have no obligation to provide you with customer support of any kind. </p>
        <h4> 3. Dispute Terms </h4>
         <h6> (a) Dispute Resolution </h6>
          <p> Disputes. To the fullest extent not prohibited by applicable law, if any controversy, allegation, or claim (including any non-contractual claim) arises out of or relates to the Service, the Content, these Terms, applicable Additional Terms, our privacy practices related to the Service and offers made on and transactions and communications conducted through the Service or to any of WhoOwnsWhat’s actual or alleged intellectual property rights (collectively, a “Dispute”), then you and we agree to send a written notice to the other providing a reasonable description of the Dispute, along with a proposed resolution of it. Our notice to you will be sent to you based on the most recent contact information that you provide us. But if no such information exists or if such information is not current, then we have no obligation under this Section 3(a). Your notice to us must be sent to: 150 Court Street, Brooklyn, NY 11201. Subject to applicable law, for a period of sixty (60) days from the date of receipt of notice from the other party, WhoOwnsWhat and you will engage in a dialogue in order to attempt to resolve the Dispute, though nothing will require either you or WhoOwnsWhat to resolve the Dispute on terms with respect to which you and WhoOwnsWhat, in each of our sole discretion, are not comfortable.</p>
          <p> Jurisdiction. The parties agree that the state or federal courts in New York, NY shall have non-exclusive jurisdiction of any Dispute, unless otherwise required by applicable laws of your jurisdiction of resident.</p>
          <p> Governing Law. To the maximum extent not prohibited by the mandatory laws in your country of residence, these Terms and any Dispute arising out of or in connection with it or its subject matter or formation (including non-contractual disputes), will be governed by, and construed in accordance with, the laws of New York without regard to its conflicts of law provisions that would apply other law.</p> 
          <p> Injunctive Relief. The foregoing provisions of this Section 3(a) will not apply to any legal action taken by WhoOwnsWhat or you to seek an injunction or other equitable relief in connection with, any potential loss, cost, or damage (or any potential loss, cost, or damage) relating to the Service, any Content, your breach of these Terms of applicable Additional Terms and/or WhoOwnsWhat’s intellectual property rights (including such WhoOwnsWhat may claim that may be in dispute), WhoOwnsWhat’s operations, and/or WhoOwnsWhat’s products or services; provided however, your rights are subject to Waiver of Certain Injunctive or Other Equitable Relief (Section 3(d)).</p>
         <h6> (b) Disclaimer Of Representations And Warranties </h6>
          <p> As Permitted By Applicable Law, The Service Is Provided On An “As Is”, “As Available”, And “With All Faults” Basis And Your Access To And Use Of The Service Is At Your Sole Risk. Therefore, to the fullest extent permissible by applicable law, WhoOwnsWhat and its direct and indirect parents, subsidiaries, affiliates and each of their respective employees, directors, members, managers, shareholders, agents, vendors, licensors, licensees, contractors, customers, successors, and assigns (collectively, “WhoOwnsWhat Parties”) hereby disclaim and make no representations, warranties, endorsements, or promises, express or implied, in connection with, or otherwise directly or indirectly related to, the Service (including the Content), including without limitation: </p>
            <ul>
            <li>(a) the functions, features, or any other elements on, or made accessible through, the Service; </li>
            <li>(b) any Content, products, services, or instructions offered, referenced, or linked through the Service; </li>
            <li>(c) security associated with your use of the Service, including UGC;</li>
            <li>(d) whether the Service or the servers that make the Service available are free from any harmful components (including viruses, Trojan horses, and other technologies that could adversely impact your Device);</li>
            <li>(e) whether the information (including any instructions) on the Service is accurate, complete, correct, adequate, useful, timely, or reliable;</li>
            <li>(f) whether any defects to or errors on the Service will be repaired or corrected; </li>
            <li>(g) whether the Service will be compatible with any other specific hardware, software or service;</li>
            <li>(h) whether your access to the Service will be uninterrupted; </li>
            <li>(i) whether the Service will be available at any particular time or location; and </li>
            <li>(j) whether your use of the Service is lawful in any particular jurisdiction. </li>
            </ul>
          <p><b> Except for any specific warranties provided herein or in additional terms provided by a whoownswhat party, as permitted by applicable law, whowonswhat parties hereby further disclaim all warranties, express or implied, including the warranties of merchantability, fitness for a particular purpose, non-infringement or misappropriation of intellectual property rights of third parties, title, custom, trade, quiet enjoyment, system integration, and freedom from computer virus. </b></p>
          <p> The warranty limitations in this Section are not intended to limit any express warranties from applicable product manufacturers of physical products sold via the Service, or any express warranties by WhoOwnsWhat that are included in applicable Additional Terms, or your remedies required under applicable law to be available to you for personal injury claims arising out of product liability, or which are otherwise not waivable under applicable law. </p>
         <h6> (c) Limitations Of Our Liability </h6>
          <p> <b>As permitted by applicable law, under no circumstances will any whoownswhat parties be responsible or liable for any loss or damages</b>, for any indirect, economic, exemplary, special, punitive, incidental, or consequential losses or damages of any kind, including without limitation loss of profits, in connection with, or otherwise directly or indirectly related to the Service (including the Content or UGC), including without limitation: </p>
            <ul>
            <li>(a) your use of or inability to use the Service, or the performance of the Service; </li>
            <li>(b) any action taken in connection with an investigation by WhoOwnsWhat Parties or law enforcement authorities regarding your access to or use of the Service; </li>
            <li>(c) any action taken in connection with copyright or other intellectual property owners or other rights owners; </li>
            <li>(d) any errors or omissions in the Service’s technical operation or security or any compromise or loss of your data or information; or </li>
            <li>(e) any damage to any user’s computer, hardware, software, modem, or other equipment or technology, including damage from any security breach or from any virus, bugs, tampering, fraud, error, omission, interruption, defect, delay in operation or transmission, computer line, or network failure or any other technical or other malfunction, including losses or damages in the form of lost profits, loss of goodwill, loss of data, work stoppage, accuracy of results, or equipment failure or malfunction.</li>
            <li>As permitted by applicable law, the foregoing limitations of liability will apply even if any of the foregoing events or circumstances were foreseeable and even if WhoOwnsWhat Parties were advised of or should have known of the possibility of such losses or damages, regardless of whether you bring an action based in contract, negligence, strict liability, or tort (including whether caused, in whole or in part, by negligence, acts of god, telecommunications failure, or destruction of the Service).</li>
            </ul> 
          <p> <b>Except as may be provided in any applicable additional terms, as permitted by applicable law, in no event will whoownswhat parties’ total liability to you, for all possible damages, losses, and causes of action in connection with your access to and use of the service and your rights under these terms, exceed an amount equal to the amount you have paid whoownswhat in connection with the transaction(s) that underlie the claim(s); provided, however, this provision will not apply if a court or tribunal with applicable jurisdiction finds such to be unconscionable. For purposes of clarity, the prior sentence does not expand or limit any express, written product warranty that is provided by whoownswhat or a manufacturer of a physical product.</b> </p>
          <p> The liability limitations in this Section are not intended to limit any express warranties from applicable product manufacturers of physical products sold by WhoOwnsWhat itself via the Service, or any express warranties by WhoOwnsWhat that are included in applicable Additional Terms, or your remedies required under applicable law to be available to you for personal injury claims arising out of product liability to the extent not waivable under applicable law. </p> 
         <h6> (d) Waiver Of Certain Injunctive Or Other Equitable Relief </h6>
          <p> <b>As permitted by applicable law, if you claim that you have incurred any loss, damages, or injuries in connection with your use of the service, then the losses, damages, and injuries will not be deemed irreparable or sufficient to entitle you to an injunction or to other equitable relief that may interfere with or prevent the development or exploitation of any website, application, content, ugc, product, service, or intellectual property owned, licensed, used or controlled by whowonswhat (including your licensed ugc) or a licensor of whoownswhat. However, such shall not limit your ability to seek other equitable relief, subject to these terms and any applicable additional terms.</b> </p>
         <h6> (e) Indemnity </h6>
          <p> As permitted by applicable law, you agree to, and you hereby, defend (if we request), indemnify, and hold WhoOwnsWhat Parties harmless from and against any and all claims, damages, losses, costs, investigations, liabilities, judgments, fines, penalties, settlements, interest, and expenses (including attorneys’ fees) that directly or indirectly arise from or are related to any claim, suit, action, demand, or proceeding made or brought against any WhoOwnsWhat Party, or on account of the investigation, defense, or settlement thereof, arising out of or in connection with, whether occurring heretofore or hereafter: (i) your UGC; (ii)your use of the Service and your activities in connection with the Service; (iii) your breach or alleged breach of these Terms or any applicable Additional Terms; (iv) your violation or alleged violation of any laws, rules, regulations, codes, statutes, ordinances, or orders of any governmental or quasi-governmental authorities in connection with your use of the Service or your activities in connection with the Service; (v) information or material transmitted through your Device, even if not submitted by you, that infringes, violates, or misappropriates any copyright, trademark, trade secret, trade dress, patent, publicity, privacy, or other right of any person or entity; (vi) any misrepresentation made by you; and (vii) WhoOwnsWhat Parties’ use of the information that you submit to us (including your UGC) subject to our Privacy Policy and applicable Additional Terms (“Claims and Losses”). You will cooperate as fully required by WhoOwnsWhat Parties in the defense of any Claim and Losses. Notwithstanding the foregoing, WhoOwnsWhat Parties retain the exclusive right to settle, compromise, and pay any and all Claims and Losses. WhoOwnsWhat Parties reserve the right to assume the exclusive defense and control of any Claims and Losses. You will not settle any Claims and Losses without, in each instance, the prior written consent of an officer of a WhoOwnsWhat Party. This section is not intended to limit any causes of action against us that you may have that are not waivable under applicable law. </p> 
        <h4> 4. Standard Terms And Conditions </h4> 
         <h6> (a) Updates To Terms. </h6> 
          <p> These Terms (or if applicable Additional Terms), in the form posted at the time of your use of the applicable services to which it applies, shall govern such use (including transactions entered during such use). <b>As our service evolves, the terms and conditions under which we offer the service may prospectively be modified and we may cease offering the service under the terms or applicable additional terms for which they were previously offered. Accordingly, each time you sign in to or otherwise use the service you are entering into a new agreement with us on the then applicable terms and conditions and you agree that we may notify you of new terms by posting them on the service (or in any other reasonable manner of notice which we elect), and that your use of the service after such notice constitutes your going forward agreement to the new terms for your new use and transactions.</b> Therefore, you should review the posted Terms, and any applicable Additional Terms, each time you use the Service. Any new Terms or Additional Terms will be effective as to new use and transactions as of the time that we post them, or such later date as may be specified in them or in other notice to you. However, the Terms (and any applicable Additional Terms) that applied when you previously used the Service will continue to apply to such prior use and any specific term to which we previously committed to apply those terms (if applicable) (i.e., changes and additions are prospective only) unless mutually agreed. In the event any notice to you of new, revised or additional terms is determined by a tribunal to be insufficient, the prior agreement shall continue until sufficient notice to establish a new agreement occurs. You should frequently check the home page, which you agree is a reasonable manner of providing you notice. You can reject any new, revised or additional terms by discontinuing use of the Service and related services. </p> 
         <h6> (b) General Provisions </h6> 
          <p> WhoOwnsWhat’s Consent or Approval. As to any provision in these Terms, or applicable Additional Terms, that grants WhoOwnsWhat a right of consent or approval, or permits WhoOwnsWhat to exercise a right in its “sole discretion,” WhoOwnsWhat may exercise that right in its sole and absolute discretion. No WhoOwnsWhat consent or approval may be deemed to have been granted by WhoOwnsWhat without being in writing and signed by an officer of WhoOwnsWhat. </p> 
          <p> Applicable Law. These Terms and any applicable Additional Terms will be governed by and construed in accordance with, and any Dispute and Excluded Dispute will be resolved in accordance with, the laws of the New York, without regard to its conflicts of law provisions that might apply the laws of another jurisdiction. </p>
          <p> Severability; Interpretation. If any provision of these Terms, or any Additional Terms, is for any reason deemed invalid, unlawful, void, or unenforceable by a court or arbitrator of competent jurisdiction, then that provision will be deemed severable from these Terms or the Additional Terms, and the invalidity of the provision will not affect the validity or enforceability of the remainder of these Terms or the applicable Additional Terms (which will remain in full force and effect). To the extent not prohibited by applicable law, you agree to waive, and you hereby waive, any applicable statutory and common law that may permit a contract to be construed against its drafter. Wherever the word “including” is used in these Terms or any applicable Additional Terms, the word will be deemed to mean “including, without limitation.” The summaries of provisions and section headings are provided for convenience only and shall not limit the full Terms. </p>
          <p> Electronic Communications and Contracting. When you communicate with us electronically, such as via email and text message, you consent to receive communications from us electronically. We will try to promptly respond to all inquiries, but we are not obligated to do so. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. You agree that any time you electronically transact, agree or consent via the Service it is intended to be an electronic signature which binds you as if you had signed on paper. You agree that your use of the Service, other than to read the Terms (or Additional Terms) and Privacy Policy, constitutes agreement to the Terms, and any applicable Additional Terms, then posted without further action by you. </p> 
          <p> Investigations; Cooperation with Law Enforcement; Termination; Survival. You agree that WhoOwnsWhat shall, as permitted by applicable law, have the right, without limitation and without any obligation, to: (i) investigate any suspected breaches of its Service security or its information technology or other systems or networks, (ii) investigate any suspected breaches of these Terms and any applicable Additional Terms or any potential harm to our users or third parties, (iii) use any information obtained by WhoOwnsWhat in accordance with its Privacy Policy in connection with reviewing law enforcement databases or complying with applicable laws and use and/or disclose any information obtained by WhoOwnsWhat to comply with law enforcement requests or legal requirements in accordance our Privacy Policy, (iv) involve and cooperate with law enforcement authorities in connection with any of the foregoing matters, (v) prosecute violators of these Terms and any applicable Additional Terms, and (vi) discontinue the Service, in whole or in part, or, except as may be expressly set forth in any applicable Additional Terms, suspend or terminate your access to it, in whole or in part, at any time, without notice, for any reason and without any obligation to you or any third party. Any suspension or termination will not affect your obligations to WhoOwnsWhat under these Terms or any applicable Additional Terms. Upon suspension or termination of your access to the Service, or upon notice from WhoOwnsWhat, all rights granted to you under these Terms or any Additional Terms will cease immediately, and you agree that you will immediately discontinue use of the Service. The provisions of these Terms and any applicable Additional Terms, which by their nature should survive your suspension or termination will survive, including the rights and licenses you grant to WhoOwnsWhat in these Terms, as well as the indemnities, releases, disclaimers, and limitations on liability and the provisions regarding jurisdiction, choice of law, no class action, jury waiver, and mandatory arbitration. </p>
          <p> Assignment. WhoOwnsWhat may assign its rights and obligations under these Terms and any applicable Additional Terms, in whole or in part, to any party at any time without any notice. These Terms and any applicable Additional Terms may not be assigned by you, and you may not delegate your duties under them, without the prior written consent of an officer of WhoOwnsWhat. </p> 
          <p> Complete Agreement; No Waiver. These Terms, and any applicable Additional Terms, reflect our complete agreement regarding the Service and supersede any prior agreements, representations, warranties, assurances or discussion related to the Services. Except as expressly set forth in these Terms or any applicable Additional Terms, (i) no failure or delay by you or WhoOwnsWhat in exercising any of rights, powers, or remedies under will operate as a waiver of that or any other right, power, or remedy, and (ii) no waiver or modification of any term of these Terms, or applicable Additional Terms, will be effective unless in writing and signed by the party against whom the waiver or modification is sought to be enforced. </p>
          <p> Devices and Connectivity. We do not warrant that the software provided by WhoOwnsWhat to utilize the Service or any other software used in connection with the Service will be compatible with other third party software nor do we warrant that operation of the Service and the associated software will not damage or disrupt other software or hardware. You are responsible for obtaining and maintaining all Devices and other equipment and software, and all internet service provider, mobile service, and other services needed for your access to and use of the Service and you will be responsible for all charges related to them. You further agree to look solely to the entity that manufactured and/or sold you the Device for any issues related to the Device and its compatibility with the Service and/or the WhoOwnsWhat software. </p> 
          <p> By using the Service, you agree that WhoOwnsWhat may change, alter, or modify the settings or configurations on your Device in order to allow for or optimize your use of the Service (e.g., save content, access data, enable services, etc.). </p> 
          <p> You must be connected to the Internet for the entire time you are using the Service, the cost and provisions of which is your responsibility. The quality of the display of the Content may vary from Device to Device, and may be affected by a variety of factors, such as your Device, your location, the bandwidth available through and/or speed of your Internet connection. WhoOwnsWhat makes no representations or warranties about the quality of your Service experience on your Device or the ability of any Device to access or display the Content. In order to stream or download Content, your equipment must meet certain system requirements, including but not limited to having high-speed Internet access. You may not download or stream Content if you are located outside any designated territory and you will not try to circumvent territory restrictions (such as by using a proxy server). Please review any restrictions, including without limitation regarding simultaneous viewing, that may be posted from time to time and which shall be Additional Terms. </p>
          <p> Any issues related to the Service and/or the WhoOwnsWhat software, including any system requirements, are covered and limited by this Agreement. Please refer to the Disclaimer of Representations and Warranties and Limitations of Liability provisions set forth in these Terms at Section 3(b) and (c). </p>
          <p> © JustFix.nyc 2018. All Rights Reserved. </p>
      </div>
      <LegalFooter />
    </div>
  );
}

export default TermsOfUsePage;