SELECT 
    M.DOCUMENTID, 
    M.DOCDATE, 
    M.DOCAMOUNT, 
    M.RECORDEDFILED, 
    M.DOCTYPE, 
    L.BBL
FROM REAL_PROPERTY_MASTER AS M
LEFT JOIN REAL_PROPERTY_LEGALS AS L 
    USING(DOCUMENTID)
WHERE M.DOCTYPE = 'DEED' 
	AND M.DOCAMOUNT > 1
	AND L.BBL = %(bbl)s
ORDER BY M.DOCDATE DESC NULLS LAST
LIMIT 1;
