SELECT 
	WOW_BLDGS.*,
	CASE 
		WHEN BBL = %(bbl)s THEN GRAPH
		ELSE NULL
	END AS GRAPH
	FROM (
		SELECT UNNEST(BBLS) BBL, GRAPH
		FROM WOW_PORTFOLIOS
		WHERE %(bbl)s = ANY(BBLS)
	) T
INNER JOIN WOW_BLDGS USING(BBL);
