SELECT 
	CASE 
		WHEN N.DEVELOPMENT IS NOT NULL THEN 'NYCHA'
		WHEN R.UC2019 > 0 THEN 'RENT-STABILIZED'
		WHEN P.UNITSRES > 0 THEN 'MARKET-RATE'
		ELSE 'UNKNOWN'
	END AS HOUSINGTYPE
FROM PLUTO_19V2 P
LEFT JOIN RENTSTAB_V2 R ON P.BBL = UCBBL
LEFT JOIN NYCHA_BBLS_18 N USING(BBL)
WHERE BBL = %(bbl)s
LIMIT 1
