-- PLUTO Building Info Query for when BBL is not found.
SELECT 
	   ADDRESS FORMATTED_ADDRESS,
	   SPLIT_PART( ADDRESS, ' ' , 1 ) HOUSENUMBER,
	   SUBSTR(ADDRESS, STRPOS(ADDRESS, ' ') + 1) STREETNAME,
     BLDGCLASS,
     CASE 
      WHEN BOROUGH = 'MN' THEN 'MANHATTAN'
      WHEN BOROUGH = 'BX' THEN 'BRONX' 
      WHEN BOROUGH = 'BK' THEN 'BROOKLYN' 
      WHEN BOROUGH = 'QN' THEN 'QUEENS' 
      WHEN BOROUGH = 'SI' THEN 'STATEN ISLAND' 
     ELSE '' END BORO,
	   LAT LATITUDE,
	   LNG LONGITUDE
   FROM PLUTO_19V2
   WHERE BBL = %(bbl)s
