-- Grab the graph json object that corresponds 
-- to the portfolio of the search address: 
WITH PORTFOLIO_GRAPH AS (
	SELECT 
		%(bbl)s as BBL,
		GRAPH
	FROM WOW_PORTFOLIOS
	WHERE %(bbl)s = ANY(BBLS)
	LIMIT 1
)

-- Select a subset of WOW_BLDGS that only contains
-- BBLs within the same portfolio
SELECT 
	WOW_BLDGS.HOUSENUMBER,
	WOW_BLDGS.STREETNAME,
	WOW_BLDGS.ZIP,
	WOW_BLDGS.BORO,
	WOW_BLDGS.REGISTRATIONID,
	WOW_BLDGS.LASTREGISTRATIONDATE,
	WOW_BLDGS.REGISTRATIONENDDATE,
	WOW_BLDGS.BBL,
	WOW_BLDGS.BIN,
	WOW_BLDGS.CORPNAMES,
	WOW_BLDGS.BUSINESSADDRS,
	WOW_BLDGS.OWNERNAMES,
	WOW_BLDGS.ALLCONTACTS,
	WOW_BLDGS.TOTALVIOLATIONS,
	WOW_BLDGS.OPENVIOLATIONS,
	WOW_BLDGS.TOTALCOMPLAINTS,
	WOW_BLDGS.RECENTCOMPLAINTS,
	WOW_BLDGS.RECENTCOMPLAINTSBYTYPE,
	WOW_BLDGS.UNITSRES,
	WOW_BLDGS.YEARBUILT,
	WOW_BLDGS.COUNCIL,
	WOW_BLDGS.LAT,
	WOW_BLDGS.LNG,
	WOW_BLDGS.EVICTIONS,
	WOW_BLDGS.RSUNITS2007,
	WOW_BLDGS.RSUNITSLATEST,
	WOW_BLDGS.RSUNITSLATESTYEAR,
	WOW_BLDGS.RSDIFF,
	WOW_BLDGS.YEARSTARTEDJ51,
	WOW_BLDGS.YEARSTARTED421A,
	WOW_BLDGS.LASTSALEACRISID,
	WOW_BLDGS.LASTSALEDATE,
	WOW_BLDGS.LASTSALEAMOUNT,
	WOW_BLDGS.EVICTIONFILINGS,
	PORTFOLIO_GRAPH.GRAPH
FROM WOW_BLDGS
LEFT JOIN PORTFOLIO_GRAPH USING(BBL)
WHERE BBL = ANY(
	SELECT UNNEST(BBLS)
	FROM WOW_PORTFOLIOS
	WHERE %(bbl)s = ANY(BBLS)
);