WITH DEVS AS (
	SELECT 
		DISTINCT DEVELOPMENT 
	FROM NYCHA_BBLS_18
	WHERE DEVELOPMENT !~ 'POLICE SERVICE AREA'
	AND BBL = %(bbl)s
),

DEV_BBLS AS (
	SELECT DISTINCT ON (BBL)
		N.DEVELOPMENT,
		N.BBL,
		P.UNITSRES, 
		E.EVICTIONS
	FROM NYCHA_BBLS_18 N
	LEFT JOIN PLUTO_19V2 P USING(BBL)
	LEFT JOIN (
		SELECT BBL, COUNT(*) EVICTIONS FROM MARSHAL_EVICTIONS_ALL 
		WHERE RESIDENTIALCOMMERCIALIND = 'RESIDENTIAL'
		GROUP BY BBL
	) E USING(BBL)
	WHERE DEVELOPMENT IN (SELECT DEVELOPMENT FROM DEVS)
)

SELECT 
	STRING_AGG(DISTINCT DEVELOPMENT, ' / ') DEVELOPMENT,
	SUM(EVICTIONS) DEV_EVICTIONS,
	SUM(UNITSRES) DEV_UNITSRES
FROM DEV_BBLS;
