WITH PLUTO AS (
    SELECT 
    	BBL,
        (COALESCE(UNITSRES, 0) < 11) AS CANT_REPORT
    FROM PLUTO_LATEST
    WHERE BBL = %(bbl)s
)
SELECT
    BBL,
    CASE WHEN 
        MAX(P.CANT_REPORT::INT)::BOOLEAN THEN NULL
        ELSE COALESCE(COUNT(DISTINCT INDEXNUMBERID), 0)::NUMERIC 
    END AS EVICTION_FILINGS
FROM PLUTO AS P
LEFT JOIN OCA_ADDRESSES_WITH_BBL AS A USING(BBL)
LEFT JOIN OCA_INDEX AS I USING(INDEXNUMBERID)
WHERE I.FILEDDATE BETWEEN %(start_date)s AND %(end_date)s
  AND I.CLASSIFICATION = any('{Holdover,Non-Payment}')
  AND I.PROPERTYTYPE = 'Residential'
GROUP BY BBL
