SELECT
  A.BBL,
  COUNT(DISTINCT INDEXNUMBERID) AS LAGGED_EVICTION_FILINGS,
  MAX(I.FILEDDATE) AS LAGGED_EVICTION_DATE
FROM OCA_METADATA AS M
INNER JOIN OCA_INDEX AS I USING(INDEXNUMBERID)
INNER JOIN OCA_ADDRESSES_WITH_BBL AS A USING(INDEXNUMBERID)
WHERE A.BBL = %(bbl)s
  AND I.CLASSIFICATION = ANY('{Holdover,Non-Payment}')
  AND I.PROPERTYTYPE = 'Residential'
  AND M.INITIALDATE > %(prev_date)s and I.FILEDDATE < %(prev_date)s and I.FILEDDATE > %(oldest_filed_date)s
GROUP BY BBL
