SELECT
    BBL,
    COUNT(*)::NUMERIC AS VIOLATIONS
FROM HPD_VIOLATIONS
WHERE BBL = %(bbl)s
AND COALESCE(NOVISSUEDDATE, INSPECTIONDATE) >= %(start_date)s
AND COALESCE(NOVISSUEDDATE, INSPECTIONDATE) < %(end_date)s
GROUP BY BBL
