from typing import NamedTuple


class HpdComplaintsAndProblems(NamedTuple):
    ReceivedDate: str = "2014-07-07"
    ProblemID: str = "14525811"
    ComplaintID: str = "6960137"
    BuildingID: str = "3418"
    Borough: str = "MANHATTAN"
    HouseNumber: str = "1989"
    StreetName: str = "ADAM C POWELL BOULEVARD"
    Postcode: str = "10026"
    Block: str = "1904"
    Lot: str = "4"
    Apartment: str = "12D"
    CommunityBoard: str = "10"
    UnitType: str = "APARTMENT"
    SpaceType: str = "ENTIRE APARTMENT"
    Type: str = "EMERGENCY"
    MajorCategory: str = "UNSANITARY CONDITION"
    MinorCategory: str = "PESTS"
    ProblemCode: str = "BED BUGS"
    ComplaintStatus: str = "CLOSE"
    ComplaintStatusDate: str = "2014-07-29"
    ProblemStatus: str = "CLOSE"
    ProblemStatusdate: str = "2014-07-28"
    StatusDescription: str = "The Department of Housing Preservation and Development inspected the following conditions. Violations were issued. Information about specific violations is available at www.nyc.gov/hpd"
    ProblemDuplicateFlag: str = "FALSE"
    ComplaintAnonymousFlag: str = "FALSE"
    UniqueKey: str = "28415899"
    Latitude: str = "40.805411999999997"
    Longitude: str = "-73.950913999999997"
    CouncilDistrict: str = "9"
    CensusTract: str = "220"
    Bin: str = "1057533"
    Bbl: str = "1019040004"
    Nta: str = "Harlem (South)"
