from typing import NamedTuple


class MarshalEvictionsAll(NamedTuple):
    uniqueid: str = ''
    bbl: str = '2031770041'
    bin: str = '2013945'
    borough: str = 'BRONX'
    censustract: str = '401'
    cleanedaddress: str = ''
    communityboard: str = '7'
    councildistrict: str = '14'
    courtindexnumber: str = '000098/17'
    docketnumber: str = '069483'
    ejectment: str = 'NOT AN EJECTMENT'
    evictionaddress: str = '65 EAST 193RD STREET'
    evictionaptnum: str = '1B'
    evictionlegalpossession: str = 'POSSESSION'
    evictionzip: str = '10468'
    executeddate: str = '2017-05-04'
    geosearchaddress: str = ''
    latitude: str = '40.866075'
    longitude: str = '-73.896515'
    marshalfirstname: str = 'HENRY'
    marshallastname: str = 'DALEY'
    nta: str = 'BEDFORD PARK FORDHAM NORTH'
    residentialcommercialind: str = 'RESIDENTIAL'
    schedulestatus: str = ''
