from typing import NamedTuple


class MarshalEvictionsAll(NamedTuple):
    bbl: str = "2031770041"
    bin: str = "2013945"
    borough: str = "BRONX"
    censustract: str = "401"
    cleaned_address: str = ""
    communityboard: str = "7"
    councildistrict: str = "14"
    courtindexnumber: str = "000098/17"
    docketnumber: str = "69483"
    ejectment: str = "NOT AN EJECTMENT"
    evictionaddress: str = "65 EAST 193RD STREET"
    evictionapartmentnumber: str = "1B"
    evictionlegalpossession: str = "POSSESSION"
    evictionpostcode: str = "10468"
    evictionzip: str = ""
    executeddate: str = "2017-05-04"
    geosearch_address: str = ""
    latitude: str = "40866075.00000000"
    longitude: str = "-73896515.00000000"
    marshal1stname: str = "HENRY"
    marshallastname: str = "DALEY"
    nta: str = "BEDFORD PARK FORDHAM NORTH"
    residentialcommercial: str = "RESIDENTIAL"
    schedulestatus: str = ""
    uniqueid: str = ""
