DROP TABLE IF EXISTS WOW_BLDGS CASCADE;

-- This is mainly used as an easy way to provide contact info on request, not a replacement
-- for cross-table analysis. Hence why the corpnames, businessaddrs, and ownernames are simplified
-- with JSON and such.
CREATE TABLE WOW_BLDGS AS 

WITH DEEDS AS (
	SELECT 
    	M.DOCUMENTID,
    	COALESCE(M.DOCDATE,M.RECORDEDFILED) DOCDATE,
    	M.DOCAMOUNT, 
    	L.BBL
	FROM REAL_PROPERTY_MASTER M
	LEFT JOIN REAL_PROPERTY_LEGALS L USING(DOCUMENTID)
	WHERE DOCAMOUNT > 1 AND DOCTYPE = ANY('{DEED,DEEDO}')
	ORDER BY DOCDATE DESC
),

FIRSTDEEDS AS (
  SELECT 
    D.BBL,
    FIRST(D.DOCUMENTID) DOCUMENTID,
    FIRST(D.DOCDATE) DOCDATE,
    FIRST(D.DOCAMOUNT) DOCAMOUNT
  FROM DEEDS D
  GROUP BY BBL
)

SELECT DISTINCT ON (REGISTRATIONS.BBL)
  REGISTRATIONS.*,
  COALESCE(VIOLATIONS.TOTAL, 0)::INT AS TOTALVIOLATIONS,
  COALESCE(VIOLATIONS.OPENTOTAL, 0)::INT AS OPENVIOLATIONS,
  PLUTO.UNITSRES,
  PLUTO.YEARBUILT,
  PLUTO.LAT,
  PLUTO.LNG,
  EVICTIONS.EVICTIONS,
  RENTSTAB.UNITSSTAB2007 AS RSUNITS2007,
  RENTSTAB.UNITSSTAB2017 AS RSUNITS2017,
  RENTSTAB.DIFF AS RSDIFF,
  RENTSTAB.PERCENTCHANGE AS RSPERCENTCHANGE,
  FIRSTDEEDS.DOCUMENTID AS LASTSALEACRISID,
  FIRSTDEEDS.DOCDATE AS LASTSALEDATE,
  FIRSTDEEDS.DOCAMOUNT AS LASTSALEAMOUNT
FROM HPD_REGISTRATIONS_WITH_CONTACTS AS REGISTRATIONS
LEFT JOIN (
  SELECT BBL,
    COUNT(CASE WHEN VIOLATIONSTATUS = 'OPEN' THEN 1 END) AS OPENTOTAL,
    COUNT(*) AS TOTAL
  FROM HPD_VIOLATIONS
  GROUP BY BBL
) VIOLATIONS ON (REGISTRATIONS.BBL = VIOLATIONS.BBL)
LEFT JOIN (
  SELECT
    BBL,
    UNITSRES,
    YEARBUILT,
    LAT, LNG
  FROM PLUTO_19V2
) PLUTO ON (REGISTRATIONS.BBL = PLUTO.BBL)
LEFT JOIN (
  SELECT
    BBL,
    COUNT(*) AS EVICTIONS
  FROM MARSHAL_EVICTIONS_18
  WHERE RESIDENTIALCOMMERCIALIND = 'RESIDENTIAL'
  GROUP BY BBL
) EVICTIONS ON (REGISTRATIONS.BBL = EVICTIONS.BBL)
LEFT JOIN (
  SELECT
    UCBBL,
    UNITSSTAB2007,
    UNITSSTAB2017,
    DIFF,
    PERCENTCHANGE
  FROM RENTSTAB_SUMMARY
) RENTSTAB ON (REGISTRATIONS.BBL = RENTSTAB.UCBBL)
LEFT JOIN FIRSTDEEDS ON (REGISTRATIONS.BBL = FIRSTDEEDS.BBL);

CREATE INDEX ON WOW_BLDGS (REGISTRATIONID);
CREATE INDEX ON WOW_BLDGS (BBL);
